### ISSUE TITLE
Support for more search tools

### ISSUE THREAD

**Issue by shrkamat** [kelly-lin/telescope-ag#4]
I usually work with very large code base, and even `rg` fails to meet grep performance requirement. I use [csearch](https://github.com/google/codesearch) (index based search) tool and it's bearable. I was wondering if this plugin can be made generic enough to adapt to any search tool.

Currently I have made some blind changes to this plugin for my own use with csearch, see - 

https://github.com/kelly-lin/telescope-ag/compare/main...shrkamat:telescope-csearch:main

I know we could expose a new command similar to `Ag` but currently the plugin name `telescope-ag` won't go well for `csearch` tool, moreover it won't be generic enough change to adapt to one another search tool.

**Comment by kelly-lin** [comment]
It is a good idea, it can definitely be made more generic. I personally use `rg` now over `ag` for performance reasons. Though, I will probably create a new plugin for it instead of amending this one. If I get around to writing it I will be sure to message you the link to the plugin.

**Comment by kelly-lin** [comment]
@shrkamat I have added a feature in the latest commit which supports any search tool and have added the instructions in the readme. Do you mind trying if it works for csearch?
